export default [{
	name: '减脂',
	subArr: [{
		img: '/static/logo.png',
		name: '红茶'
	}, {
		img: '/static/logo.png',
		name: '红茶'
	}, {
		img: '/static/logo.png',
		name: '红茶'
	}, {
		img: '/static/logo.png',
		name: '红茶'
	}, {
		img: '/static/logo.png',
		name: '红茶'
	}]
}, {
	name: '增重',
	subArr: [{
		img: '/static/logo.png',
		name: '红茶'
	}, {
		img: '/static/logo.png',
		name: '红茶'
	}]
}, {
	name: '正常',
	subArr: [{
		img: '/static/logo.png',
		name: '红茶2'
	}, {
		img: '/static/logo.png',
		name: '红茶2'
	}]
}, {
	name: '湘菜',
	subArr: [{
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}]
}, {
	name: '川菜',
	subArr: [{
		img: '/static/logo.png',
		name: '悲剧2'
	}, {
		img: '/static/logo.png',
		name: '悲剧2'
	}]
}, {
	name: '粤菜',
	subArr: [{
		img: '/static/logo.png',
		name: '红茶'
	}, {
		img: '/static/logo.png',
		name: '红茶'
	}, {
		img: '/static/logo.png',
		name: '红茶'
	}, {
		img: '/static/logo.png',
		name: '红茶'
	}, {
		img: '/static/logo.png',
		name: '红茶'
	}]
}, {
	name: '京菜',
	subArr: [{
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}, {
		img: '/static/logo.png',
		name: '水果2'
	}]

}]
